name: NetflixClone
options:
  deploymentTarget:
    iOS: '18.0'

  createIntermediateGroups: true
  xcodeVersion: 15.4

packages:
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI.git
    from: "2.2.6"

# SETTINGS

settings: 
  base:
    ALWAYS_SEARCH_USER_PATHS: NO
    BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    CODE_SIGN_IDENTITY: iPhone Developer
    CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
    CODE_SIGN_STYLE: Manual
    CURRENT_PROJECT_VERSION: 1
    ENABLED_BITCODE: NO
    ENABLE_TESTABILITY: NO
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    MARKETING_VERSION: 1.0.0
    ONLY_ACTIVE_ARCH: YES
    PRODUCT_NAME: $(TARGET_NAME)
    PROVISIONING_PROFILE: 
    PROVISIONING_PROFILE_SPECIFIER:
    SKIP_INSTALL: NO

# SCHEMES

schemes:
  NetflixCloneSample:
    build:
      targets:
        NetflixCloneSample: all
    run:
      additionalOptions:
        zoobinObjects: true
      commandLineArguments:
        "-FIRDebugEnabled" : true
        "-FIRAnalyticsDebugEnabled" : true
      config: Debug
      debugEnabled: true

  NetflixClone:
    build:
      targets:
        NetflixClone: all
        NetflixCloneTests: [test]
        NetflixCloneUITests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - NetflixClone
      targets:
        - name: NetflixCloneTests
          parallelizable: false
      environmentVariables:
        - variable: FB_REFERENCE_IMAGE_DIR
          value: $(SOURCE_ROOT)/NetflixCloneTests/ReferenceImages
          isEnabled: true
        - variable: IMAGE_DIFF_DIR
          value: $(SOURCE_ROOT)/NetflixCloneTests/FailureDiffs
          isEnabled: true
  
  NetflixCloneUITests:
    build:
      targets:
        NetflixCloneUITests: all
    test:
      gatherCoverageData: true
      targets:
        - name: NetflixCloneUITests
          parallelizable: false

# TARGETS

targets:
  NetflixCloneSample:
    type: application
    platform: iOS
    sources: 
      - path: NetflixCloneSample
        name: NetflixCloneSample
    settings:
      base:
        INFOPLIST_FILE: NetflixCloneSample/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vitorneves.NetflixCloneSample
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
        PROVISIONING_PROFILE: 
        PROVISIONING_PROFILE_SPECIFIER:
        BUILD_LIBRARY_FOR_DISTRIBUTION: NO
    dependencies:
      - target: NetflixClone
        codeSign: true
        embed: true
    postBuildScript:
      - script: scripts/swiftlint.sh
        name: Swiftlint

  NetflixClone:
    type: framework
    platform: iOS
    dependencies:
      - package: SDWebImageSwiftUI
    sources: 
      - path: NetflixClone
    settings:
      base:
        INFOPLIST_FILE: NetflixClone/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vitorneves.NetflixClone
        ENABLE_TESTABILITY: YES
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    postBuildScript:
      - script: scripts/swiftlint.sh
        name: Swiftlint

  NetflixCloneTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: NetflixClone
        embed: true
    sources: 
      - path: NetflixCloneTests
        excludes: 
          - "FailureDiffs/*"
          - "ReferenceImages/*"
          - "ReferenceImages_64/*"
        name: NetflixCloneTests
    postBuildScript:
      - script: scripts/swiftlint.sh
        name: Swiftlint
    settings:
      base:
        INFOPLIST_FILE: NetflixCloneTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vitorneves.NetflixCloneTests

  NetflixCloneUITests:
    type: bundle.ui-testing
    platform: iOS
    dependencies:
      - target: NetflixCloneSample
        embed: true
    sources: 
      - path: NetflixCloneUITests
        name: NetflixCloneUITests
    settings:
      base:
        INFOPLIST_FILE: NetflixCloneUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vitorneves.NetflixCloneUITests

aggregateTargets:
  XCFramework:
    buildScripts:
      - script: scripts/buildxcframework.sh
        name: Generate XCFramework
